name: CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Compilacion
        run: |
          mvn package
          #echo 'package'

      - name: EjecucionTestUnitarios
        run: |
          mvn package test

      - name: Generar informe JaCoCo
        run: |
          mvn jacoco:report

      - name: Publicar informe JaCoCo
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
          token: ${{ secrets.TOKEN_JACOCO}}
          #min-coverage-overall: 90
          #min-coverage-changed-files: 60

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Analisis SonarCloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{secrets.SONAR_TOKEN}} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=lukasrl \
          -Dsonar.projectKey=LukasRL_microservicio-java

      - name: SonarQube Quality Gate Check
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        with:
          scanMetadataReportFile: target/sonar/report-task.txt
          
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USER_TOKEN_DOCKER }}
          password: ${{ secrets.TOKEN_DOCKER }}

      - name: Docker build
        run: 
          docker build -t lukasrl/ms-mensaje:lates .

      - name: Docker push
        run: 
          docker push lukasrl/ms-mensaje:lates